title: George Saad
description: I'm a Master's student at the University of Toronto, doing research in Large Langue Models (LLMs) and Recommender Systems (RecSys) with Prof. Scott Sanner. I have extensive experience in AI & software through many projects and internships.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
logo: assets/img/profile.png